name: say-my-name
run-name: running npm package which display my information
on:
  push:
    branches: ['main']
jobs:
  markdown-lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: run npx command
        run: npx xkeshav --yes
